### ISSUE TITLE
Clarification on Base64 padding characters

### ISSUE THREAD

**Issue by roryhewitt** [paulehoffman/draft-ietf-doh-dns-over-https#17]
In Section 5.1, it says 

> Padding characters for base64url MUST NOT be included.

Presumably this is because, in GET format, this would result in extraneous `=` signs in the URL? What happens if someone (or an automated system) pastes a Base64 request including padding characters?

**Comment by paulehoffman** [comment]
The purpose of "MUST NOT" is to say that a receiver is not expected to be able to parse them.
